checks:
    python:
        code_rating: true
        duplicate_code: true

build:
  dependencies:
    before:
      - pip install importlib-resources
      - pip install poetry==1.0.5
      - poetry config virtualenvs.create false
      - poetry install

  tests:
    override:
      - tox

  nodes:
    py36:
      dependencies:
        before:
          - pip install importlib-resources

      environment:
        python: 3.6.0

    py37:
      environment:
        python: 3.7.2

    py38:
      environment:
        python: 3.8.0

      tests:
        override:
          - tox
          - py-scrutinizer-run
