checks:
    python:
        code_rating: true
        duplicate_code: true

build:
  environment:
    python: 3.8.0

  dependencies:
    before:
      - pip install poetry==1.0.5
      - poetry config virtualenvs.create false
      - poetry install

  tests:
    override:
      - tox
      - py-scrutinizer-run
